<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $schematic_helper     = $this->helper('imagemarker');
    $_productCollection = $schematic_helper->getSchematicCategoryCollection($_category->getId());
    $layer_collection = $schematic_helper->getLayerCollection($_category->getId());
    
    $_imgHtml   = '';
    if ($_category->getSchematic()) {
        $_imgUrl = Mage::getBaseUrl('media').'catalog'.DS.'category'.DS.$_category->getSchematic();
        $image = getimagesize($_imgUrl);


        if($image[0]>750):
            $file_path = 'catalog' . DS . 'category' . DS . $_category->getSchematic();
            $old_width = $image[0];
            $old_height = $image[1];
            $height = $image[1] / $image[0] * 750;
            $_imgUrl = $schematic_helper->CategorySchematicResize($file_path, 750, $height);
            $image = getimagesize($_imgUrl);

            $width_change = (($old_width - $image[0]) * 100 ) / $old_width;
            if($image[1] < $old_height){
                $height_change = (($old_height - $image[1]) * 100 ) / $old_height;               
            }
            $note_html = '';
            foreach($layer_collection as $layer): 
                $width = $layer->getWidth() - (($layer->getWidth() * $width_change) / 100);
                $height = $layer->getHeight() - (($layer->getHeight() * $height_change) / 100);
                $left = $layer->getLeft() - (($layer->getLeft() * $width_change) / 100);
                $top = $layer->getTop() - (($layer->getTop() * $height_change) / 100);  
                $note_html .= '<div id="note_'.$layer->getId().'" data-top="'.$top.'" data-left="'.$left.'" data-width="'.$width.'" data-height="'.$height.'"></div>'; 
            endforeach;
        else:
            $note_html = '';
            foreach($layer_collection as $layer): 
                $note_html .= '<div id="note_'.$layer->getId().'" data-top="'.$layer->getTop().'" data-left="'.$layer->getLeft().'" data-width="'.$layer->getWidth().'" data-height="'.$layer->getHeight().'"></div>'; 
            endforeach;
        endif;

        

        $_imgHtml = '<div id="dumpty-aspect-data" style="display:none;"  data-height="'.$image[1].'" data-width="'.$image[0].'">'.$note_html.'</div><div class="schematic-image"><img id="toAnnotate" src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" style="height:'.$image[1].'; width:'.$image[0].';" /></div>';
        
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<ul class="messages-spl-cat messages" style="display:none;">
	<li class="main-message-ajax">
		<ul>
			<li>
				<span>&nbsp;</span>
			</li>
		</ul>
	</li>
</ul>
<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
<?php endif; ?>

<div class="schematic-data cat-id">
    <form name="schematic-layer" id="schematic-layer">
        <?php if(Mage::getSingleton('customer/session')->isLoggedIn()) {
            $customer = Mage::getSingleton('customer/session')->getCustomer();
        } ?>
        <input type="hidden" name="name" id="customer_name" value="<?php if(Mage::getSingleton('customer/session')->isLoggedIn()) {  echo $customer->getName(); } ?>" />
        <input type="hidden" name="email" id="customer_email" value="<?php if(Mage::getSingleton('customer/session')->isLoggedIn()) {  echo $customer->getEmail(); } ?>" />
        <input type="hidden" name="phone" id="customer_phone" value="<?php if(Mage::getSingleton('customer/session')->isLoggedIn()) { $customerAddressId = $customer->getDefaultBilling(); if($customerAddressId){  $address = Mage::getModel('customer/address')->load($customerAddressId); echo $address->getTelephone(); } } ?>" />
    </form>
    <div class="data-table " id="schematic-table" style="position:relative;">
        <div class="schematic-body">            
            <div class="schematic-inner-data">
                <?php if(Mage::Helper('imagemarker/device')->isMobile() && !Mage::Helper('imagemarker/device')->isTablet()) { ?>
                    <div class="mobile-message"><div class="zoom-message"><?php echo $this->__('zoom + tab to select a part or scroll down') ?></div></div>
                <?php } ?>
                <div class="main-schemantic-image" style=" display: block;">  <!-- width: 62%;  <?php echo $image[0]; ?>px; padding: 0px 10px;  -->
                    <?php if($_imgUrl): ?>
                        <?php echo $_imgHtml ?>
                    <?php endif; ?>
                </div>
                <div class="product-data" style=" display: block;"> <!-- padding: 0px 10px;  width: 37%; -->
                    <?php if($_productCollection->count()): ?>                            
                    <table id="schematic-products-table" class="data-table">
                        <colgroup>
                        <?php if($image[0]<700): ?>
                            <col>
                        <?php else: ?>
                            <col width="95">
                        <?php endif; ?>
                            <col>
                            <col width="185">
                            <!--<col width="15">-->
                        </colgroup>
                        <thead>
                            <tr class="headings">
                                <th class=""><?php echo $this->__('Part No'); ?></th>
                                <th class=""><?php echo $this->__('Description'); ?></th>
                                <th class="a-center">&nbsp;</th>
                                <!--<th class="">&nbsp;</th>-->
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($layer_collection as $layer): ?>
                                <?php if(empty($layer->getProductIds())): continue; endif; ?>
                                <?php $layer_products = explode(',', $layer->getProductIds()); ?>
                                <?php foreach ($_productCollection as $product): ?>
                                    <?php if(!in_array($product->getId(), $layer_products)):  continue; endif; ?>
                                    <tr class="layer-row row-<?php echo $layer->getId(); ?>" id="<?php echo $product->getId(); ?>" style="border-color: rgb(250, 191, 143); border-style: none; background: none repeat scroll 0% 0% rgb(255, 255, 255);">
                                        <td class="prod-sku"><?php echo $product->getSku(); ?></td>
                                        <td class="prod-name"><?php echo $product->getName(); ?></td>
                                        <td class="prod-action">
                                            <?php $product_list_block = new Mage_Catalog_Block_Product_List; ?>
                                            <form action="<?php echo $product_list_block->getAddToCartUrl($product); ?>" method="post">
                                                <div class="no-display">
                                                    <input type="hidden" value="<?php echo $product->getId(); ?>" name="product">
                                                </div>
                                                <?php if($product->isSaleable()): ?>
                                                    <div class="add-to-cart-buttons">
                                                        <input type="text" class="input-text qty" title="<?php echo $this->__('Qty'); ?>" value="1" maxlength="12" id="qty" name="qty" pattern="\d*">
                                                        <button onclick="return schematic_addtocart(this);" type="submit" class="button btn-cart" title="<?php echo $this->__('Add to Cart'); ?>"><span><span><?php echo $this->__('+'); ?></span></span></button>
                                                    </div>
                                                <?php endif; ?>
                                            </form>
                                            <?php unset($product_list_block); ?>
                                        </td>
                                        <!--<td class="a-center">
                                            <?php if($product->isSaleable()): ?>
                                                <div id="cart-count-<?php echo $product->getId(); ?>"><?php if($item_qty = $schematic_helper->getProductQty($product)): echo $item_qty; else: echo 0; endif; ?> 
                                                </div>
                                            <?php endif; ?>
                                        </td>-->
                                    </tr>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script language="javascript">
    jQuery(window).load(function() {        
        
        /*
        var width = jQuery('.main-schemantic-image').width();
        var parentWidth = jQuery('.main-schemantic-image').offsetParent().width();
        var percent = 100*width/parentWidth;
        if(percent >= 80){
            percent = 62.5;
        }        
        jQuery('.main-schemantic-image').width(percent+'%');
        if(percent != 100){
            jQuery('.product-data').width((100-percent-1)+'%');
        }

        jQuery("#toAnnotate").annotateImage({
            getUrl: '<?php echo $this->getUrl('imagemarker/index/index', array('category_id' => $_category->getId())); ?>',
            saveUrl: '<?php echo $this->getUrl('imagemarker/index/send', array('category_id' => $_category->getId())); ?>',
            deleteUrl: '<?php echo $this->getUrl('imagemarker/index/count', array('category_id' => $_category->getId())); ?>',
            editable: true,
            useAjax: true,            
        });   */
    });
    
    jQuery(document).ready(function() { 
        //var width = jQuery('.main-schemantic-image').width();
        var width = <?php echo $image[0]; ?>;
        var parentWidth = jQuery('.main-schemantic-image').offsetParent().width();
        var percent = 100*width/parentWidth;
        if(percent >= 80){
            percent = 62.5;
        }
        jQuery('.main-schemantic-image').width(percent+'%');
        if(percent != 100){
            jQuery('.product-data').width((100-percent-1)+'%');
        }

        jQuery("#toAnnotate").annotateImage({
            getUrl: '<?php echo $this->getUrl('imagemarker/index/index', array('category_id' => $_category->getId())); ?>',
            saveUrl: '<?php echo $this->getUrl('imagemarker/index/send', array('category_id' => $_category->getId())); ?>',
            deleteUrl: '<?php echo $this->getUrl('imagemarker/index/count', array('category_id' => $_category->getId())); ?>',
            editable: true,
            useAjax: true,
            /*notes:  [
                    <?php foreach($layer_collection as $layer): ?>
                        { 
                          "top": <?php echo $layer->getTop(); ?>,
                          "left": <?php echo $layer->getLeft(); ?>,
                          "width": <?php echo $layer->getWidth(); ?>,
                          "height": <?php echo $layer->getHeight(); ?>,
                          "text": "<?php echo $layer->getText(); ?>",
                          "id": <?php echo $layer->getId(); ?>,
                          "editable": true 
                        },
                    <?php endforeach; ?>
                    ]*/
        });   

        jQuery(".layer-row").on('mouseenter mouseleave', function(e) {
            var get = jQuery.grep(this.className.split(" "), function(v, i){
               return v.indexOf('row') === 0;
           }).join();
           layer = get.split("-")[1];
           jQuery(".layer"+layer).trigger(e.type);
        });

        jQuery("#schematic-products-table").mouseleave(function() {
            jQuery(".layer-row").removeClass('on-mouse');
        });		
    });

    jQuery.fn.resizeHeightMaintainRatio = function(newHeight){
        var aspectRatio = jQuery(this).data('aspectRatio');
        if (aspectRatio == undefined) {
            aspectRatio = jQuery(this).width() / jQuery(this).height();
            jQuery(this).data('aspectRatio', aspectRatio);
        }
        jQuery(this).height(newHeight); 
        jQuery(this).width(parseInt(newHeight * aspectRatio));
    }

    jQuery.fn.resizeWidthMaintainRatio = function(newWidth){
        var aspectRatio = jQuery(this).data('aspectRatio');
        if (aspectRatio == undefined) {
            aspectRatio = jQuery(this).height() / jQuery(this).width();
            jQuery(this).data('aspectRatio', aspectRatio);
        }        
        jQuery(this).width(newWidth); 
        jQuery(this).height(parseInt(newWidth * aspectRatio));
    }

    jQuery.fn.stickyfloat = function(options, lockBottom) {

        var obj = this;
        var floaty = obj.offset().top;
        var footery = jQuery('.footer-container').offset().top;
        var startOffset = obj.parent().offset().top;
        var parentPaddingTop = startOffset - obj.parent().parent().offset().top;
        var opts = jQuery.extend({ startOffset: startOffset, offsetY: parentPaddingTop, duration: 200, lockBottom:true }, options);
        var originalWidth = obj.width();

        if(opts.lockBottom) {
            var bottomPos = footery - (obj.outerHeight() + floaty + startOffset); // + 14 //get the maximum scrollTop value
            if (bottomPos < 0) {
                bottomPos = 0;
            }
        }
        
     //   if(bottomPos > obj.outerHeight()) {
            
            obj.css('width', originalWidth + 'px');
            obj.css({ position: 'absolute', top : parentPaddingTop+ 'px'});

            function updateFloat() {
                
                obj.stop(); // stop all calculations on scroll event
                var scrollTop = jQuery(document).scrollTop();
                
                var footery = jQuery('.footer-container').offset().top;
                if(opts.lockBottom){
                    var bottomPos = footery - (obj.outerHeight() + floaty ); // + 14  //get the maximum scrollTop value
                    if( bottomPos < 0 )
                        bottomPos = 0;
                }

                var pastStartOffset         = scrollTop > opts.startOffset; // check if the window was scrolled down more than the start offset declared.
                var objFartherThanTopPos    = obj.offset().top > startOffset;   // check if the object is at it's top position (starting point)
                var objBiggerThanWindow     = obj.outerHeight() < jQuery(window).height();  // if the window size is smaller than the Obj size, then do not animate.

                // if window scrolled down more than startOffset OR obj position is greater than
                // the top position possible (+ offsetY) AND window size must be bigger than Obj size
                // if( (pastStartOffset || objFartherThanTopPos) && objBiggerThanWindow )
                if((pastStartOffset || objFartherThanTopPos)) {
                
                    var newpos = ((scrollTop - startOffset) + parentPaddingTop);
                    if (newpos > ((bottomPos ) + parentPaddingTop)) { // + 14
                        newpos = bottomPos + parentPaddingTop - 31;
                    }
                    if ( scrollTop < (parentPaddingTop)) { //  - 14 // if window scrolled < starting offset, then reset Obj position (opts.offsetY);
                        newpos = parentPaddingTop; // - 14
                    }
                    if(newpos < parentPaddingTop) {
                        newpos = parentPaddingTop;  // - 14
                    }
                    
                    obj.animate({ top: newpos }, opts.duration );
                }
            }
            
            if(window.location.hash) {
                updateFloat();
            }

            jQuery(window).scroll(function () {
                if(jQuery(window).width() > 640){
                    updateFloat();
                }
            });


        //}
    };

    jQuery(window).on('resize', function() {
        if(jQuery(window).width() > 640){
            var img_height = jQuery('.schematic-image').outerHeight();
            var prod_list = jQuery('#schematic-products-table').outerHeight();
            if(prod_list>img_height){
                jQuery('.schematic-image').stickyfloat({ duration: 100 });
            }            
        }
        else{
            jQuery('.schematic-image').css('position', 'relative');
            jQuery('.schematic-image').css('top', '0px');
        }
        jQuery('.image-annotate-canvas').resizeWidthMaintainRatio(jQuery('.main-schemantic-image').width());
        jQuery('.image-annotate-view').resizeWidthMaintainRatio(jQuery('.main-schemantic-image').width());
        jQuery('.image-annotate-edit').resizeWidthMaintainRatio(jQuery('.main-schemantic-image').width());
        if((jQuery('.main-schemantic-image').width() == jQuery('#dumpty-aspect-data').attr('data-width'))  || (parseInt(jQuery('.main-schemantic-image').width()) == parseInt(jQuery('#dumpty-aspect-data').attr('data-width'))-2)) {
            jQuery(".image-annotate-view .image-annotate-area").each(function( index ) {
                var get = jQuery.grep(this.className.split(" "), function(v, i){
                   return v.indexOf('layer-edit') === 0;
                }).join();
                layer = get.split("-")[2];
                var width = parseInt(jQuery('#note_'+layer).attr('data-width'));
                var height = parseInt(jQuery('#note_'+layer).attr('data-height'));
                var left = parseInt(jQuery('#note_'+layer).attr('data-left'));
                var top = parseInt(jQuery('#note_'+layer).attr('data-top'));                
                jQuery(this).css('left', left+'px');
                jQuery(this).css('top', top+'px');
                jQuery(this).children().css('width', width+'px');
                jQuery(this).children().css('height', height+'px');
                jQuery('#layer-note-'+layer).css('left', left+'px');
                jQuery('#layer-note-'+layer).css('top', parseInt(top+height+2)+'px');
            });

        }
        else if (jQuery('.main-schemantic-image').width() > jQuery('#dumpty-aspect-data').attr('data-width')) {
            width_change = ((jQuery('.main-schemantic-image').width() - jQuery('#dumpty-aspect-data').attr('data-width')) * 100 ) / jQuery('#dumpty-aspect-data').attr('data-width');
            if(jQuery('.schematic-image').height() > jQuery('#dumpty-aspect-data').attr('data-height')){
                height_change = ((jQuery('.schematic-image').height() - jQuery('#dumpty-aspect-data').attr('data-height')) * 100 ) / jQuery('#dumpty-aspect-data').attr('data-height');
            }

            jQuery(".image-annotate-view .image-annotate-area").each(function( index ) {
                var get = jQuery.grep(this.className.split(" "), function(v, i){
                   return v.indexOf('layer-edit') === 0;
                }).join();
                layer = get.split("-")[2];
                var width = parseInt(jQuery('#note_'+layer).attr('data-width')) + parseInt((jQuery('#note_'+layer).attr('data-width') * width_change) / 100);
                var height = parseInt(jQuery('#note_'+layer).attr('data-height')) + parseInt((jQuery('#note_'+layer).attr('data-height') * height_change) / 100);
                var left = parseInt(jQuery('#note_'+layer).attr('data-left')) + parseInt((jQuery('#note_'+layer).attr('data-left') * width_change) / 100);
                var top = parseInt(jQuery('#note_'+layer).attr('data-top')) + parseInt((jQuery('#note_'+layer).attr('data-top') * height_change) / 100);                
                jQuery(this).css('left', left+'px');
                jQuery(this).css('top', top+'px');
                jQuery(this).children().css('width', width+'px');
                jQuery(this).children().css('height', height+'px');
                jQuery('#layer-note-'+layer).css('left', left+'px');
                jQuery('#layer-note-'+layer).css('top', parseInt(top+height+2)+'px');
            });
        }
        else if (jQuery('.main-schemantic-image').width() < jQuery('#dumpty-aspect-data').attr('data-width')) {
            width_change = ((jQuery('#dumpty-aspect-data').attr('data-width') - jQuery('.main-schemantic-image').width()) * 100 ) / jQuery('#dumpty-aspect-data').attr('data-width');
            if(jQuery('.schematic-image').height() < jQuery('#dumpty-aspect-data').attr('data-height')){
                height_change = ((jQuery('#dumpty-aspect-data').attr('data-height') - jQuery('.schematic-image').height()) * 100 ) / jQuery('#dumpty-aspect-data').attr('data-height');               
            }
            
            jQuery(".image-annotate-view .image-annotate-area").each(function( index ) {
                var get = jQuery.grep(this.className.split(" "), function(v, i){
                   return v.indexOf('layer-edit') === 0;
                }).join();
                layer = get.split("-")[2];
                var width = parseInt(jQuery('#note_'+layer).attr('data-width')) - parseInt((jQuery('#note_'+layer).attr('data-width') * width_change) / 100);
                var height = parseInt(jQuery('#note_'+layer).attr('data-height')) - parseInt((jQuery('#note_'+layer).attr('data-height') * height_change) / 100);
                var left = parseInt(jQuery('#note_'+layer).attr('data-left')) - parseInt((jQuery('#note_'+layer).attr('data-left') * width_change) / 100);
                var top = parseInt(jQuery('#note_'+layer).attr('data-top')) - parseInt((jQuery('#note_'+layer).attr('data-top') * height_change) / 100);                
                jQuery(this).css('left', left+'px');
                jQuery(this).css('top', top+'px');
                jQuery(this).children().css('width', width+'px');
                jQuery(this).children().css('height', height+'px');
                jQuery('#layer-note-'+layer).css('left', left+'px');
                jQuery('#layer-note-'+layer).css('top', parseInt(top+height+2)+'px');
            });
        }
        else{

        }

    });



    jQuery(document).ready(function() {
        if(jQuery(window).width() > 640){
            var img_height = jQuery('.schematic-image').outerHeight();
            var prod_list = jQuery('#schematic-products-table').outerHeight();
            if(prod_list>img_height){
                jQuery('.schematic-image').stickyfloat({ duration: 100 });
            }
        }
        else{
            jQuery('.schematic-image').css('position', 'relative');
            jQuery('.schematic-image').css('top', '0px');
        }

        jQuery(document).click(function(event) {
            var container = jQuery("#image-annotate-edit-form");
            if (!container.is(event.target) && container.has(event.target).length === 0)
            {
                jQuery('.image-annotate-edit-close').trigger('click');                
                jQuery('.image-annotate-view').hide();
                jQuery('.image-annotate-view').show();
            }
        });

        var hitEvent = 'ontouchstart' in document.documentElement ? 'touchstart' : 'click';
        jQuery('.btn-cart').bind(hitEvent, function() { schematic_addtocart(this); return; });
           
    });

    function show_set_product(hide, show){
        document.getElementById('show-set'+hide).style.display = 'none';
        document.getElementById('show-set'+show).style.display = 'block';
    }

    function schematic_addtocart(form){
        if(jQuery(form).is("button")){
            var form = jQuery(form).parents('form:first');
        }
        var url = null;
        if(!url){
            url = jQuery(form).attr('action');
        }
        url = url.replace("checkout/cart","imagemarker/checkout_cart"); 
        url += 'isAjax/true/';

        /*var isMobile = {
            Android: function() {
                return navigator.userAgent.match(/Android/i);
            },
            BlackBerry: function() {
                return navigator.userAgent.match(/BlackBerry/i);
            },
            iOS: function() {
                return navigator.userAgent.match(/iPhone|iPad|iPod/i);
            },
            Opera: function() {
                return navigator.userAgent.match(/Opera Mini/i);
            },
            Windows: function() {
                return navigator.userAgent.match(/IEMobile/i);
            },
            any: function() {
                return (isMobile.Android() || isMobile.BlackBerry() || isMobile.iOS() || isMobile.Opera() || isMobile.Windows());
            }
        };*/
             
        jQuery.ajax({
            url: url,
            dataType: 'json',
            type : 'post',
            data: form.serialize(),
            success: function(data){
                //jQuery('#cart-count-'+data.product_id).html(data.count);
                if(data.status == 'SUCCESS'){
                    if(jQuery('.header-minicart')){
                        jQuery('.header-minicart').html(data.toplink);
                    }
                	if(jQuery('.main-message-ajax').hasClass('error-msg')){
						jQuery('.main-message-ajax').removeClass('error-msg');
					}
                	jQuery('.main-message-ajax').addClass('success-msg');
                	jQuery('.main-message-ajax.success-msg li span').html(data.message);
                    jQuery('.messages-spl-cat').fadeIn(1000);
                    //if(isMobile.any()) {
                    <?php if(Mage::Helper('imagemarker/device')->isMobile()  && !Mage::Helper('imagemarker/device')->isTablet()) { ?>
                        jQuery('.messages-spl-cat').css('position', 'fixed');
                        jQuery('.messages-spl-cat').css('z-index', '9');
                        jQuery('.messages-spl-cat').css('top', '0px');
                    //}
                    <?php } ?>
                }
                else{
					if(data.status == 'ERROR'){
						if(jQuery('.main-message-ajax').hasClass('success-msg')){
							jQuery('.main-message-ajax').removeClass('success-msg');
						}
	                	jQuery('.main-message-ajax').addClass('error-msg');
	                	jQuery('.main-message-ajax.error-msg li span').html(data.message);                   
	                	jQuery('.messages-spl-cat').fadeIn(1000);   
                        //if(isMobile.any()) {
                        <?php if(Mage::Helper('imagemarker/device')->isMobile()  && !Mage::Helper('imagemarker/device')->isTablet()) { ?>
                            jQuery('.messages-spl-cat').css('position', 'fixed');
                            jQuery('.messages-spl-cat').css('z-index', '9');
                            jQuery('.messages-spl-cat').css('top', '0px');
                        //}  
                        <?php } ?>                
                	}
                }
                setTimeout(function() {
                    jQuery('.messages-spl-cat').fadeOut(1000);
                }, 5000);

            }
        });
        return false;
    }
</script>
<script type="text/javascript">
    decorateTable('schematic-table')
</script>



<?php /*if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; */ ?>
